PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE users(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    username TEXT NOT NULL,
    hash TEXT NOT NULL,
    email TEXT NOT NULL);
INSERT INTO users VALUES(1,'John Doe','scrypt:32768:8:1$sSJdcsxL4H5XESc2$ad0103357bc8bcc05ea06dd9b2b9c7913c3ae2c4ba6711b2f30251ca7c6a104a1fe4aec289d9a6a9c598ae4873a8f11b6fec74c6f6396cf73f405cd872fd3ec3','flowey@gmail.com');
CREATE TABLE history(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    user_id INTEGER NOT NULL,
    input_line TEXT NOT NULL,
    algorithm_scan TEXT NOT NULL,
    gpt_scan TEXT NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
    );
INSERT INTO history VALUES(1,1,'litora, multum ille et terris iactatus et alto',replace('Original line: \nlitora, multum ille et terris iactatus et alto\n\nStep 1: lītora mūltum īlle ēt tērris iāctātŭs ĕt āltō\n\nStep 2: lītŏră mūltum_īlle_ēt tērrīs iāctātŭs ĕt āltō\n\nFinal Scansion:\nLSS, LL, LL, LL, LSS, LX\nDactyl, Spondee, Spondee, Spondee, Dactyl, Trochee\nlītŏră|| mūltum_ī||lle_ēt tē||rrīs iā||ctātŭs ĕ||t āltō\n\nElision between: multum ille\nElision between: ille et','\n',char(10)),replace('1. Line with elisions marked:\n"litora, multum ille et terris iactatus et alto"\n\n2. Division into syllables:\nli-to-ra, mul-tum il-le et ter-ris i-ac-ta-tus et al-to\n\n3. Marking every syllable as long by nature, long by position, or short:\n- li (short) - the vowel ''i'' is not followed by a consonant that would make it long.\n- to (short) - the vowel ''o'' is not followed by a consonant that would make it long.\n- ra (short) - the vowel ''a'' is not followed by a consonant that would make it long.\n- mul (short) - the vowel ''u'' is not followed by a consonant that would make it long.\n- tum (short) - the vowel ''u'' is not followed by a consonant that would make it long.\n- il (short) - the vowel ''i'' is not followed by a consonant that would make it long.\n- le (short) - the vowel ''e'' is not followed by a consonant that would make it long.\n- et (short) - the conjunction ''et'' is short.\n- ter (short) - the vowel ''e'' is not followed by a consonant that would make it long.\n- ris (short) - the vowel ''i'' is not followed by a consonant that would make it long.\n- i (short) - the vowel ''i'' is not followed by a consonant that would make it long.\n- ac (short) - the vowel ''a'' is not followed by a consonant that would make it long.\n- ta (short) - the vowel ''a'' is not followed by a consonant that would make it long.\n- tus (short) - the vowel ''u'' is not followed by a consonant that would make it long.\n- et (short) - the conjunction ''et'' is short.\n- al (short) - the vowel ''a'' is not followed by a consonant that would make it long.\n- to (short) - the vowel ''o'' is not followed by a consonant that would make it long.\n\n4. Identifying and numbering all six metrical feet:\n1. li-to-ra (dactyl)\n2. mul-tum (spondee)\n3. il-le (dactyl)\n4. et ter (spondee)\n5. ris i (dactyl)\n6. ac-ta-tus (dactyl)\n\n5. Final scansion in metrical notation:\n– ∪ ∪ | – – | ∪ ∪ | – – | ∪ ∪ | – – \n\n6. Line with macrons/breves applied to the syllables:\nlītōrā, multum ille et terrīs iāctātus et altō','\n',char(10)),'2025-11-23 05:34:20');
INSERT INTO history VALUES(2,1,'litora, multum ille et terris iactatus et alto',replace('Original line: \nlitora, multum ille et terris iactatus et alto\n\nStep 1: lītora mūltum īlle ēt tērris iāctātŭs ĕt āltō\n\nStep 2: lītŏră mūltum_īlle_ēt tērrīs iāctātŭs ĕt āltō\n\nFinal Scansion:\nLSS, LL, LL, LL, LSS, LX\nDactyl, Spondee, Spondee, Spondee, Dactyl, Trochee\nlītŏră|| mūltum_ī||lle_ēt tē||rrīs iā||ctātŭs ĕ||t āltō\n\nElision between: multum ille\nElision between: ille et','\n',char(10)),replace('1. Line with elisions marked:\n"litora, multum ille et terris iactatus et alto"\n\n2. Division into syllables:\nli-to-ra, mul-tum il-le et ter-ris i-ac-ta-tus et al-to\n\n3. Marking every syllable as long by nature, long by position, or short:\n- li (short) - a single consonant before a vowel\n- to (short) - a single consonant before a vowel\n- ra (short) - a single consonant before a vowel\n- mul (short) - a single consonant before a vowel\n- tum (short) - a single consonant before a vowel\n- il (short) - a single consonant before a vowel\n- le (short) - a single consonant before a vowel\n- et (short) - a single consonant before a vowel\n- ter (short) - a single consonant before a vowel\n- ris (short) - a single consonant before a vowel\n- i (short) - a single consonant before a vowel\n- ac (short) - a single consonant before a vowel\n- ta (short) - a single consonant before a vowel\n- tus (short) - a single consonant before a vowel\n- et (short) - a single consonant before a vowel\n- al (short) - a single consonant before a vowel\n- to (short) - a single consonant before a vowel\n\n(Note: All syllables are short, and there are no elisions in this line.)\n\n4. Identifying and numbering all six metrical feet:\n1. (li-to-ra) - dactyl\n2. (mul-tum) - spondee\n3. (il-le et) - spondee\n4. (ter-ris) - spondee\n5. (i-ac-ta-tus) - dactyl\n6. (et al-to) - spondee\n\n5. Final scansion in metrical notation:\n– ∪ | – – | – – | – – | ∪ – | – –\n\n6. Line with macrons/breves applied to the syllables:\nlītorā, multum illē et terrīs iāctātus et altō','\n',char(10)),'2025-11-23 23:13:51');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('users',1);
INSERT INTO sqlite_sequence VALUES('history',2);
COMMIT;
